# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pberge <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/24 18:46:58 by pberge            #+#    #+#              #
#    Updated: 2019/10/21 11:52:53 by pberge           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
FLAGS = -Wall -Wextra -Werror
DEL = rm -f
SRC = ft_memset.c	ft_memalloc.c	ft_tolower.c	\
		  ft_toupper.c	ft_isprint.c	ft_isascii.c	\
		  ft_isalpha.c	ft_isdigit.c	ft_isalnum.c	\
		  ft_bzero.c	ft_memcpy.c		ft_memccpy.c	\
		  ft_memmove.c	ft_strlen.c		ft_memchr.c		\
		  ft_memcmp.c	ft_strdup.c		ft_strcpy.c		\
		  ft_strncpy.c	ft_strcat.c		ft_strncat.c	\
		  ft_strlcat.c	ft_strchr.c		ft_strrchr.c	\
		  ft_strstr.c	ft_strcmp.c		ft_strnstr.c	\
		  ft_strncmp.c	ft_atoi.c		ft_memdel.c		\
		  ft_strnew.c	ft_strdel.c		ft_strclr.c		\
		  ft_striter.c	ft_striteri.c	ft_strmap.c		\
		  ft_strmapi.c	ft_strequ.c		ft_strnequ.c	\
		  ft_strsub.c	ft_strjoin.c	ft_strtrim.c	\
		  ft_strsplit.c	ft_itoa.c		ft_putchar.c	\
		  ft_putstr.c	ft_putendl.c	ft_putnbr.c		\
		  ft_putchar_fd.c	ft_putstr_fd.c	\
		  ft_putendl_fd.c	ft_putnbr_fd.c	\
		  ft_lstnew.c	ft_lstdelone.c	ft_lstdel.c		\
		  ft_lstadd.c	ft_lstiter.c	ft_lstmap.c		\
		  ft_islower.c	ft_isupper.c	ft_swap_ints.c	\
		  ft_iterative_power.c			\
		  ft_recursive_power.c			\
		  ft_lstadd_to_end.c			ft_strrcpy.c	\
		  get_next_line.c

OBJF = obj/
OBJ_ = $(SRC:.c=.o)
OBJ = $(addprefix $(OBJF), $(OBJ_))

$(NAME): $(OBJ) $(OBJF)
	@ar rc $(NAME) $(OBJ)

all: $(NAME)

$(OBJF)%.o : %.c
	@gcc $(CFLAGS) -c $< -o $@

$(OBJF):
	@mkdir $(OBJF)

clean:
	@$(DEL) $(OBJ)

fclean: clean
	@$(DEL) $(NAME)

re:
	@make fclean all
